language: node_js
node_js:
  - node
install:
  - yarn add
  - yarn add -g vsce
script:
  - yarn compile
  - vsce package
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: '*.vsix'
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: vsce publish -p $VSCE_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
notifications:
  email:
    recipients:
      - $ADMIN_EMAIL
    on_success: change
    on_failure: always
